export const STRINGS = {
  login: {
    title: 'Sign In',
    nameLabel: 'Name',
    namePlaceholder: 'Enter user name',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter password',
    forgotPassword: 'Forgot password?',
    signInButton: 'Sign in',
    googleLogin: 'G Login with google',
    noAccount: "Don't have an account? ",
    signUp: 'Sign up',
  },
  signup: {
    title: 'Sign Up',
    label: 'Create Account',
    name: 'Name',
    namePlaceholder: 'Cheguevaran',
    email: 'Email',
    emailPlaceholder: 'cheguevaran007@gmail.com',
    password: 'Password',
    passwordPlaceholder: '•••••••••••••••••',
    confirmPassword: 'Confirm password',
    confirmPasswordPlaceholder: '•••••••••••••••••',
    button: 'Sign Up',
    alreadyHaveAccount: 'Already have an account? ',
    login: 'Sign In',
  },
  splash: {
    title: 'Business Suite',
    subtitle: 'your business, simplified',
    description: 'Manage parties, sales, staff and inventory all in one place.',
    button: 'Get Started',
  },
  onboarding: {
    skip: 'Skip',
    next: 'Continue',
    previous: 'Back',
    done: 'Get Started',
    steps: [
      {
        title: 'Manage Parties\n& Accounts',
        description: 'Add customers and vendors, track outstanding balances, and manage all your account relationships in one place.',
      },
      {
        title: 'Sales Orders\n& Invoices',
        description: 'Create and track sales orders, manage invoices and run your complete billing workflow with ease.',
      },
      {
        title: 'Staff & Route\nManagement',
        description: 'Assign routes to your field team, track daily attendance and monitor visits and collections in real time.',
      },
    ],
  },
  common: {
    back: '←',
    loading: 'Loading...',
    openSettings: 'Open Settings',
    notNow: 'Not Now',
    privacyPolicy: 'Privacy Policy',
    termsCondition: 'Terms & Conditions',
    privacyUrl: 'https://policies.google.com/privacy',
    termsUrl: 'https://policies.google.com/terms',
    byContinuing: 'By continuing, you agree to our ',
    and: ' and ',
  },
  permissions: {
    camera: {
      title: 'Camera Access Required',
      message: 'We need access to your camera to allow you to take profile photos and scan QR codes.',
    },
    gallery: {
      title: 'Gallery Access Required',
      message: 'We need access to your photo library to let you upload images and documents directly from your device.',
    },
    location: {
      title: 'Location Access Required',
      message: 'We need your location to show relevant nearby services and ensure accurate delivery tracking.',
    },
    microphone: {
      title: 'Microphone Access Required',
      message: 'We need access to your microphone to enable voice commands and audio recording features.',
    },
    audio: {
      title: 'Audio Access Required',
      message: 'We need access to your media library to allow you to select and play audio files within the app.',
    },
    notifications: {
      title: 'Notification Access Required',
      message: 'We need permission to send you important updates, order status notifications, and alerts.',
    },
  },
  otp: {
    title: 'OTP Verification',
    subtitle: 'Enter the 4-digit verification code sent to your registered email address.',
    resend: 'Resend Code',
    verify: 'Verify & Proceed',
    timer: 'Resend code in ',
    errorEmpty: 'Please enter the 4-digit code',
    success: 'Account successfully verified!',
    failed: 'Verification failed. Please try again.',
    resent: 'Verification code resent!',
  },
  storefront: {
    title: 'Storefront',
    searchPlaceholder: 'Search products, grocery...',
    catalogTitle: 'Featured Catalog',
    itemsFound: '{count} Items Found',
    noItems: 'No matching items found',
    sortFilters: 'Sort & Filters',
    selectCategory: 'Select Category',
    sortBy: 'Sort By',
    reset: 'Reset',
    applyFilters: 'Apply Filters',
    defaultSort: 'Default',
    alphabeticalSort: 'Alphabetical (A-Z)',
    lowToHighSort: 'Price: Low to High',
    highToLowSort: 'Price: High to Low',
    wishlistComingSoon: 'Wishlist feature coming soon!',
    checkoutComingSoon: 'Checkout feature coming soon!',
  },
};
