export const STRINGS = {
  login: {
    title: 'Sign In',
    nameLabel: 'Name',
    namePlaceholder: 'Enter user name',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Enter password',
    forgotPassword: 'Forgot password?',
    signInButton: 'Sign in',
    googleLogin: 'G Login with google',
    noAccount: "Don't have an account? ",
    signUp: 'Sign up',
  },
  signup: {
    title: 'Sign Up',
    label: 'Create Account',
    name: 'Name',
    namePlaceholder: 'Cheguevaran',
    email: 'Email',
    emailPlaceholder: 'cheguevaran007@gmail.com',
    password: 'Password',
    passwordPlaceholder: '•••••••••••••••••',
    confirmPassword: 'Confirm password',
    confirmPasswordPlaceholder: '•••••••••••••••••',
    button: 'Sign Up',
    alreadyHaveAccount: 'Already have an account? ',
    login: 'Sign In',
  },
  splash: {
    title: 'Grocery Shop',
    subtitle: 'at your door',
    description: 'The easiest way to buy your grocery shopping',
    button: 'Get Started',
  },
  onboarding: {
    skip: 'Skip',
    next: 'Continue',
    previous: 'Back',
    done: 'Get Started',
    steps: [
      {
        title: 'Premium Quality\nFresh Grocery',
        description: 'Discover the finest selection of organic fruits and hand-picked vegetables delivered straight from local farms to your kitchen.',
        image: 'https://cdn-icons-png.flaticon.com/512/3081/3081840.png',
      },
      {
        title: 'Flash Fast\nDoorstep Delivery',
        description: 'Your time is precious. Experience lightning-fast delivery within 30 minutes, ensuring your groceries arrive fresh and on time.',
        image: 'https://cdn-icons-png.flaticon.com/512/2830/2830305.png',
      },
      {
        title: 'Secure & Seamless\nPayments',
        description: 'Pay with absolute peace of mind. Supporting all major credit cards, digital wallets, and convenient cash on delivery options.',
        image: 'https://cdn-icons-png.flaticon.com/512/1019/1019607.png',
      },
    ],
  },
  common: {
    back: '←',
    loading: 'Loading...',
    openSettings: 'Open Settings',
    notNow: 'Not Now',
    privacyPolicy: 'Privacy Policy',
    termsCondition: 'Terms & Conditions',
    privacyUrl: 'https://policies.google.com/privacy',
    termsUrl: 'https://policies.google.com/terms',
    byContinuing: 'By continuing, you agree to our ',
    and: ' and ',
  },
  permissions: {
    camera: {
      title: 'Camera Access Required',
      message: 'We need access to your camera to allow you to take profile photos and scan QR codes.',
    },
    gallery: {
      title: 'Gallery Access Required',
      message: 'We need access to your photo library to let you upload images and documents directly from your device.',
    },
    location: {
      title: 'Location Access Required',
      message: 'We need your location to show relevant nearby services and ensure accurate delivery tracking.',
    },
    microphone: {
      title: 'Microphone Access Required',
      message: 'We need access to your microphone to enable voice commands and audio recording features.',
    },
    audio: {
      title: 'Audio Access Required',
      message: 'We need access to your media library to allow you to select and play audio files within the app.',
    },
    notifications: {
      title: 'Notification Access Required',
      message: 'We need permission to send you important updates, order status notifications, and alerts.',
    },
  },
  otp: {
    title: 'OTP Verification',
    subtitle: 'Enter the 4-digit verification code sent to your registered email address.',
    resend: 'Resend Code',
    verify: 'Verify & Proceed',
    timer: 'Resend code in ',
    errorEmpty: 'Please enter the 4-digit code',
    success: 'Account successfully verified!',
    failed: 'Verification failed. Please try again.',
    resent: 'Verification code resent!',
  },
  storefront: {
    title: 'Storefront',
    searchPlaceholder: 'Search products, grocery...',
    catalogTitle: 'Featured Catalog',
    itemsFound: '{count} Items Found',
    noItems: 'No matching items found',
    sortFilters: 'Sort & Filters',
    selectCategory: 'Select Category',
    sortBy: 'Sort By',
    reset: 'Reset',
    applyFilters: 'Apply Filters',
    defaultSort: 'Default',
    alphabeticalSort: 'Alphabetical (A-Z)',
    lowToHighSort: 'Price: Low to High',
    highToLowSort: 'Price: High to Low',
    wishlistComingSoon: 'Wishlist feature coming soon!',
    checkoutComingSoon: 'Checkout feature coming soon!',
  },
};
