import { accountGroupTypeDefs } from "./accountgroups";
import { accountTypeDefs } from "./accounts";
import { adminTypeDefs } from "./admin";
import { branchTypeDefs } from "./branches";
import { brandTypeDefs } from "./brands";
import { categoryTypeDefs } from "./categories";
import { modelTypeDefs } from "./models";
import { paymentTypeDefs } from "./payments";
import { productGroupTypeDefs } from "./productgroups";
import { productServiceTypeDefs } from "./products";
import { purchaseInvoiceTypeDefs } from "./purchaseinvoice";
import { salesInvoiceTypeDefs } from "./salesinvoice";
import { salesmenAccountTypeDefs } from "./salesmenaccount";
import { sizeTypeDefs } from "./size";
import { subCategoryTypeDefs } from "./subcategories";
import { transactionTypeDefs } from "./transactions";
import { transferStockTypeDefs } from "./transferstock";
import { unitTypeDefs } from "./units";
import { uploadTypeDefs } from "./uploads";

export const typeDefs = [branchTypeDefs, categoryTypeDefs, subCategoryTypeDefs, sizeTypeDefs, brandTypeDefs, modelTypeDefs, productGroupTypeDefs, accountGroupTypeDefs, accountTypeDefs, unitTypeDefs, salesmenAccountTypeDefs, uploadTypeDefs, productServiceTypeDefs, salesInvoiceTypeDefs, purchaseInvoiceTypeDefs, transferStockTypeDefs, adminTypeDefs, transactionTypeDefs, paymentTypeDefs];