import { accountGroupResolvers } from "./accountgroups";
import { accountLedgerResolvers } from "./accountledgers";
import { accountResolvers } from "./accounts";
import { adminResolvers } from "./admin";
import { branchResolvers } from "./branches";
import { brandResolvers } from "./brands";
import { categoryResolvers } from "./categories";
import { modelResolvers } from "./models";
import { paymentResolvers } from "./payments";
import { productGroupResolvers } from "./productgroups";
import { productServiceResolvers } from "./products";
import { purchaseInvoiceResolvers } from "./purchaseinvoice";
import { salesInvoiceResolvers } from "./salesinvoice";
import { staffAccountResolvers } from "./staffaccounts";
import { sizeResolvers } from "./size";
import { subCategoryResolvers } from "./subcategories";
import { transactionResolvers } from "./transactions";
import { transferStockResolvers } from "./transferstock";
import { unitResolvers } from "./units";
import { uploadResolvers } from "./uploads";
import { expenseNoteResolvers } from "./expensenote";

export const resolvers = [branchResolvers, categoryResolvers, subCategoryResolvers ,sizeResolvers, brandResolvers, modelResolvers, productGroupResolvers, accountGroupResolvers, accountLedgerResolvers, accountResolvers, unitResolvers, staffAccountResolvers, uploadResolvers, productServiceResolvers, salesInvoiceResolvers, purchaseInvoiceResolvers, transferStockResolvers, adminResolvers, transactionResolvers, paymentResolvers, expenseNoteResolvers];